[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "timber_nds"
authors = [{name = "Angel Navarro-Mora", email = "ahnavarro@itcr.ac.cr"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/ingahnavarro/timber_nds"
